sudo: false

language: node_js
node_js: "10"

deploy:
  # Make a commit and a tag if an update was found.
  - provider: script
    script: node scripts/update-issues && node scripts/update-table && node scripts/push
    skip_cleanup: true
    on:
      branch: master
      condition: $TRAVIS_EVENT_TYPE = cron
